version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sneakers-addict-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sneakers_addict
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sneakers_addict_pgdata:/var/lib/postgresql/data

volumes:
  sneakers_addict_pgdata:
